<a href="https://colab.research.google.com/github/dongju12/python/blob/main/numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [6]:
import numpy as np

list_data = [1 ,2 ,3]
array = np.array(list_data)

print(array.size)

3


In [9]:
array1 = np.arange(4)
print(array1)

[0 1 2 3]


In [13]:
array2 = np.zeros((4, 4),dtype=float)
print(array2)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [16]:
array3 = np.ones((3,3),dtype=str)
print(array3)

[['1' '1' '1']
 ['1' '1' '1']
 ['1' '1' '1']]


In [19]:
array4 = np.random.randint(0, 10, (3, 3)) #랜덤
print(array4)

[[0 0 3]
 [4 5 9]
 [4 8 5]]


In [23]:
#평균 0 표준편차 1
array5 = np.random.normal(0, 1,(3, 3))
print(array5)

[[ 1.31247002  0.8505425   0.78757342]
 [ 1.47628462  0.85510524  0.49921879]
 [ 0.87943766 -0.24777911 -0.30460047]]


In [26]:
ar1 = np.array([1, 2, 3])
ar2 = np.array([4, 5, 6])
ar3 = np.concatenate([ar1, ar2])

print(ar3)

[1 2 3 4 5 6]


In [28]:
ar4 = np.array([1, 2, 3, 4])
ar5 = ar4.reshape((2, 2))

print(ar5)

[[1 2]
 [3 4]]


In [33]:
ar6 = np.arange(4).reshape(1, 4)
ar7 = np.arange(8).reshape(2, 4)

print(ar6)
print(ar7)

ar8 = np.concatenate([ar6, ar7], axis=0)
print(ar8)


[[0 1 2 3]]
[[0 1 2 3]
 [4 5 6 7]]
[[0 1 2 3]
 [0 1 2 3]
 [4 5 6 7]]


In [38]:
array = np.arange(8).reshape(2, 4)
left, right = np.split(array, [2], axis=1)
print(left.shape)
print(right.shape)
print(array)
print(left)

(2, 2)
(2, 2)
[[0 1 2 3]
 [4 5 6 7]]
[[0 1]
 [4 5]]


In [41]:
array = np.random.randint(1, 10, size=4).reshape(2, 2)
print(array)

[[8 1]
 [6 2]]


In [43]:
result_array = array * 10
print(result_array)

[[80 10]
 [60 20]]


In [45]:
array1 = np.arange(4).reshape(2, 2)
array2 = np.arange(2)

array3 = array1 + array2
print(array3)

[[0 2]
 [2 4]]


In [48]:
array1 = np.arange(0, 8).reshape(2, 4)
array2 = np.arange(0, 8).reshape(2, 4)
array3 = np.concatenate([array1, array2], axis=0)
array4 = np.arange(0, 4).reshape(4, 1)

print(array3+array4)

[[ 0  1  2  3]
 [ 5  6  7  8]
 [ 2  3  4  5]
 [ 7  8  9 10]]


In [52]:
ar1 = np.arange(16).reshape(4, 4)
print(ar1)

ar2 = ar1 < 10
print(ar2)

ar1[ar2] = 100
print(ar1)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]
[[ True  True  True  True]
 [ True  True  True  True]
 [ True  True False False]
 [False False False False]]
[[100 100 100 100]
 [100 100 100 100]
 [100 100  10  11]
 [ 12  13  14  15]]


In [55]:
ar1 = np.arange(16).reshape(4, 4)
print("최대값: ", np.max(ar1))
print("최소값: ", np.min(ar1))
print("합계: ", np.sum(ar1))
print("평균값: ", np.mean(ar1))

print("합계: ", np.sum(ar1, axis=0))

최대값:  15
최소값:  0
합계:  120
평균값:  7.5
합계:  [24 28 32 36]


In [58]:
array = np.arange(0, 10)
np.save('saved.npy', array)

result = np.load('saved.npy')
print(result)

[0 1 2 3 4 5 6 7 8 9]


In [61]:
array1 = np.arange(0, 10)
array2 = np.arange(10, 20)
np.savez('saved.npz', array1=array1, array2=array2)

data = np.load('saved.npz')
result1 = data['array1']
result2 = data['array2']
print(result1)
print(result2)

[0 1 2 3 4 5 6 7 8 9]
[10 11 12 13 14 15 16 17 18 19]


In [64]:
array = np.array([5, 9, 10, 3, 1])
array.sort()
print(array)

[ 1  3  5  9 10]


In [69]:
array = np.array([[5, 9, 10, 3, 1],[8, 3, 4, 2, 5]])
print(array)
array.sort(axis=0)
print(array)

[[ 5  9 10  3  1]
 [ 8  3  4  2  5]]
[[ 5  3  4  2  1]
 [ 8  9 10  3  5]]


In [73]:
array = np.linspace(0, 10, 5)
print(array)

np.random.seed(7)
print(np.random.randint(0, 10, (2, 3)))

[ 0.   2.5  5.   7.5 10. ]
[[4 9 6]
 [3 3 7]]


In [75]:
ar1 = np.arange(0, 10)
ar2 = ar1.copy()
ar2[0] = 99
print(ar1)

[0 1 2 3 4 5 6 7 8 9]


In [76]:
array = np.array([1, 1, 2, 2, 2, 3, 3, 4])
print(np.unique(array))

[1 2 3 4]
